115;9ucursor            #60d4fe
cursor_text_color #003343

foreground            #e2e2e2
background            #131313
selection_foreground  #1d323a
selection_background  #b4cad5
url_color             #60d4fe

#: black 000000 767676
color0  #000000
color8  #000000
#: red cc0403 f2201f
color1  #ffb2b9
color9  #ffb2b9
#: green 19cb00 23fd00
color2  #7bda9c
color10 #7bda9c
#: yellow cecb00 fffd00
color3  #b2d26b
color11 #b2d26b
#: blue 0d73cc 1a8fff
color4  #afc6ff
color12 #afc6ff
#: magenta cb1ed1 fd28ff
color5  #eab2ff
color13 #eab2ff
#: cyan 0dcdcd 14ffff
color6  #50d7ed
color14 #50d7ed
#: white dddddd ffffff
color7  #FFFFFF
color15 #FFFFFF

mark1_foreground #003343
mark1_background #60d4fe
mark2_foreground #1d323a
mark2_background #b4cad5
mark3_foreground #2c2c4b
mark3_background #c5c3ea

active_tab_foreground #001f29
active_tab_background #baeaff
inactive_tab_foreground #ffffff
inactive_tab_background #005971

active_border_color #60d4fe
inactive_border_color #003343
