115;9ucursor            #ffb2bd
cursor_text_color #5d0f26

foreground            #e2e2e2
background            #131313
selection_foreground  #41282c
selection_background  #e5bdc1
url_color             #ffb2bd

#: black 000000 767676
color0  #000000
color8  #000000
#: red cc0403 f2201f
color1  #ffb3b3
color9  #ffb3b3
#: green 19cb00 23fd00
color2  #b1d26c
color10 #b1d26c
#: yellow cecb00 fffd00
color3  #e4c44a
color11 #e4c44a
#: blue 0d73cc 1a8fff
color4  #cebdff
color12 #cebdff
#: magenta cb1ed1 fd28ff
color5  #ffafd6
color13 #ffafd6
#: cyan 0dcdcd 14ffff
color6  #50d7ee
color14 #50d7ee
#: white dddddd ffffff
color7  #FFFFFF
color15 #FFFFFF

mark1_foreground #5d0f26
mark1_background #ffb2bd
mark2_foreground #41282c
mark2_background #e5bdc1
mark3_foreground #432906
mark3_background #eabf90

active_tab_foreground #400014
active_tab_background #ffd9de
inactive_tab_foreground #ffffff
inactive_tab_background #8b3447

active_border_color #ffb2bd
inactive_border_color #5d0f26
