115;9ucursor            #4cd9e0
cursor_text_color #003537

foreground            #e2e2e2
background            #131313
selection_foreground  #1a3334
selection_background  #b1cccd
url_color             #4cd9e0

#: black 000000 767676
color0  #000000
color8  #000000
#: red cc0403 f2201f
color1  #ffb595
color9  #ffb595
#: green 19cb00 23fd00
color2  #7bda9c
color10 #7bda9c
#: yellow cecb00 fffd00
color3  #b2d26b
color11 #b2d26b
#: blue 0d73cc 1a8fff
color4  #afc6ff
color12 #afc6ff
#: magenta cb1ed1 fd28ff
color5  #eab2ff
color13 #eab2ff
#: cyan 0dcdcd 14ffff
color6  #4cdadd
color14 #4cdadd
#: white dddddd ffffff
color7  #FFFFFF
color15 #FFFFFF

mark1_foreground #003537
mark1_background #4cd9e0
mark2_foreground #1a3334
mark2_background #b1cccd
mark3_foreground #1d2f4a
mark3_background #b5c7e9

active_tab_foreground #002021
active_tab_background #6ff6fd
inactive_tab_foreground #ffffff
inactive_tab_background #005b5f

active_border_color #4cd9e0
inactive_border_color #003537
