//define the shell
shell /usr/bin/zsh

//include the matugen generated colors
include colors.conf

//padding
window_padding_width 20

//Map Ctrl+C to copy text, and Ctrl+V to past text
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

//Map Ctrl+Shift+C to interrupt/kill processes (replaces old Ctrl+C)
map ctrl+shift+c send_text all \x03

