general {
	# avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock
    # lock before suspend.
    before_sleep_cmd = loginctl lock-session1
    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

#--------------Dimming
listener {
    timeout = 100
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
listener {
    timeout = 90
    on-timeout = notify-send "Idle" "Screen dimming..."
}

listener {
    timeout = 300 
    on-timeout = loginctl lock-session
}
listener {
    timeout = 290
    on-timeout = notify-send "Idle" "Locking session..."
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r 
}
